### ISSUE TITLE
Openbox right click context menu doesn't open with srdt

### ISSUE THREAD

**Issue by sheepy0125** [dot1nt/srdt#4]
Openbox has a context menu that opens when you right click on the desktop. With srdt, however, the context menu doesn't open due to the srdt window capturing the mouse click instead.

A possible fix I've thought of is on a click that's not a left click, destroy the srdt window and send another click in the same spot. Then, create the window again.

I'm willing to make a pull request for this with this or another fix. Would you be interested in one?

**Comment by dot1nt** [comment]
Maybe moving the window lower with XLowerWindow() works. If it doesn't work you can make a PR. Thanks
